version: 2.1

orbs:
  node: circleci/node@5.0.3
          
jobs:
  build_and_test:
    docker:
      - image: cimg/node:16.18
    executor: node/default
    working_directory: ~/market/frontend
    steps:
      - checkout:
          path: ~/market
      - node/install-packages:
          pkg-manager: yarn
      - run:
          command: yarn test
          name: Run tests
      - run:
          command: yarn build
          name: Build app
      - persist_to_workspace:
          root: ~/market/frontend
          paths: .


# Invoke jobs via workflows
# See: https://circleci.com/docs/2.0/configuration-reference/#workflows
workflows:
  build_test_deploy:
    jobs:
      - build_and_test

